module.exports={
    output:{
        filename:'[name].js'
    },
    devServer:{
        open:true,
        port:12300,
        proxy:{
            '/react-static':{
                target:'http://localhost:12301',
                changeOrigin:true,
                secure:false
            },
            '/vue-static':{
                target:'http://localhost:12302',
                changeOrigin:true,
                secure:false
            }
        }
    }
}